---
name: nginx

releases:
- name: nginx-boshrelease
  version: latest

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: nginx
  instances: 1
  azs: [ z1 ]
  vm_type: default
  persistent_disk_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: nginx
    release: nginx-boshrelease
    properties:
      port: 8080
update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
